//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBot.Model
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Paziente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paziente()
        {
            this.DiarioPaziente = new HashSet<DiarioPaziente>();
            this.FenotipoPaziente = new HashSet<FenotipoPaziente>();
        }
    
        public long IdPaziente { get; set; }
        public string CodiceFiscale { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime DataPrimoInserimento { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public System.DateTime DataNascita { get; set; }
        public string ConversationId { get; set; }
        public string FromId { get; set; }
        public string FromName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiarioPaziente> DiarioPaziente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FenotipoPaziente> FenotipoPaziente { get; set; }
    }
}
