//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBot.Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ValoriNutrizionali
    {
        public string Nome { get; set; }
        public int Pezzi { get; set; }
        public decimal Grammi { get; set; }
        public decimal CarboidratiSemplici { get; set; }
        public decimal CarboidratiComplessi { get; set; }
        public decimal Fibre { get; set; }
        public decimal Proteine { get; set; }
        public decimal Acqua { get; set; }
    }
}
